export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  SHOW_THEME_VIEW: 'SHOW_THEME_VIEW',
  LANGUAGE_LOAD_SUCCESS: 'LANGUAGE_LOAD_SUCCESS',
  TRENDING_REFRESH: 'TRENDING_REFRESH',
  TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS',
  TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL',
  TRENDING_LOAD_MORE_FAIL: 'TRENDING_LOAD_MORE_FAIL',
  TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS'
}